version: '3'

services:
    laravel.test:
        build:
            context: docker/php/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sandwicher-php8.0/app
        container_name: sandwicher-app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sandwicher-network
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        container_name: sandwicher-database
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-sandwicher}'
            MYSQL_DATABASE: '${DB_DATABASE:-sandwicher}'
            MYSQL_USER: '${DB_USERNAME:-sandwicher}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-sandwicher}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sandwicher-mysql:/var/lib/mysql'
        networks:
            - sandwicher-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]

networks:
    sandwicher-network:
        driver: bridge

volumes:
    sandwicher-mysql:
        driver: local
